- name: My playbook
  hosts: bdsol-aci51-apic1
  gather_facts: no

  tasks:
  - name: Create EPG
    ansible.builtin.include_role:
      name: create-aci-epg
    loop: '{{ epgs }}'
    vars:
      local_tenant: '{{ item.tenant }}'
      local_app: '{{ item.app }}'
      local_epg: '{{ item.epg }}'

