
- name: Set aci_login
  set_fact:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

- name: Set debug msg
  set_fact:
    debug_msg: "{{ local_tenant }} {{ local_app }} {{ local_epg }}"
- name: Show debug msg
  debug:
    var: debug_msg


- name: Add a new tenant
  cisco.aci.aci_tenant:
    <<: *aci_login
    tenant: '{{ local_tenant }}'
  delegate_to: localhost

- name: Add a new app
  cisco.aci.aci_ap:
    <<: *aci_login
    tenant: '{{ local_tenant }}'
    ap: '{{ local_app }}'
  delegate_to: localhost

- name: Add a new epg
  cisco.aci.aci_epg:
    <<: *aci_login
    tenant: '{{ local_tenant }}'
    ap: '{{ local_app }}'
    epg: '{{ local_epg }}'
  delegate_to: localhost

#- name: Pickup hostvars
#  set_fact:
#    myVars: "{{ hostvars[inventory_hostname] | list }}"

#- name: Show facts
#  debug:
#    var: hostvars[ansible_host][item2]
#  loop: "{{ myVars }}"
#  loop_control:
#    loop_var: 'item2'

